### ISSUE TITLE
"Ansible Log" tab shows all zeros; need help debugging

### ISSUE THREAD

**Issue by msabramo** [andreizhuk/tc-ansible-runner#7]
Thank you for writing this and sharing it!!!

So I set this up and at least a few times, it seemed to work properly in that it reported reasonable-looking statistics in the "Ansible Log" tab.

But after tinkering around with my build configuration, I seem to have done something that it didn't like. I don't know what. Here's what I get though. In the "Ansible Log" tab:

<img width="644" alt="screen shot 2015-10-25 at 6 49 33 am" src="https://cloud.githubusercontent.com/assets/305268/10715932/a0fe9926-7ae4-11e5-88f8-3686957d45e1.png">

In the "Build Log" tab, I see:

<img width="601" alt="screen shot 2015-10-25 at 6 51 02 am" src="https://cloud.githubusercontent.com/assets/305268/10715936/d361ed5a-7ae4-11e5-9ab4-01e8a52bc21f.png">

Which agent logs should I be looking at? Maybe the error message should indicate the specific filename that I should be looking for?

In `/home/teamcity/logs/teamcity-agent.log` on the agent, I see:

```
[2015-10-25 07:01:57,739]   INFO -    jetbrains.buildServer.AGENT - Done publishing artifacts from [/home/teamcity/temp/buildTmp/ansible-run-report.json] to [.teamcity/ansible-run], using 'ArtifactsCachePublisher', total files published: 1
[2015-10-25 07:01:57,747]   INFO -    jetbrains.buildServer.AGENT - Done publishing artifacts from [/home/teamcity/temp/buildTmp/ansible-run-report.json] to [.teamcity/ansible-run], using 'WebPublisher', total files published: 1
[2015-10-25 07:01:57,747]   INFO -    jetbrains.buildServer.AGENT - Done: Publishing files
[2015-10-25 07:01:57,747]   INFO -    jetbrains.buildServer.AGENT - Publishing artifacts process finished
```

**Comment by msabramo** [comment]
Ah, just found this in `/home/teamcity/logs/output.log`:

```
[2015-10-25 07:10:58,558]  ERROR - AnsibleReportArtifatcsProvider - Failed to generate ansible run report
java.lang.NullPointerException
        at ee.elinyo.teamcity.plugins.ansible.logparser.AnsibleOutputProcessor.nextTask(AnsibleOutputProcessor.java:72)
        at ee.elinyo.teamcity.plugins.ansible.logparser.AnsibleOutputProcessor.process(AnsibleOutputProcessor.java:37)
        at ee.elinyo.teamcity.plugins.ansible.logparser.AnsibleOutputProcessor.onLine(AnsibleOutputProcessor.java:24)
        at ee.elinyo.teamcity.plugins.ansible.agent.AnsibleReportArtifatcsProvider.getPlaybook(AnsibleReportArtifatcsProvider.java:110)
        at ee.elinyo.teamcity.plugins.ansible.agent.AnsibleReportArtifatcsProvider.generateReport(AnsibleReportArtifatcsProvider.java:78)
        at ee.elinyo.teamcity.plugins.ansible.agent.AnsibleReportArtifatcsProvider.beforeBuildFinish(AnsibleReportArtifatcsProvider.java:53)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120)
        at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:67)
        at com.sun.proxy.$Proxy6.beforeBuildFinish(Unknown Source)
        at jetbrains.buildServer.agent.impl.buildStages.finishStages.FireBeforeBuildFinishFStage.doFinishStage(FireBeforeBuildFinishFStage.java:32)
        at jetbrains.buildServer.agent.impl.buildStages.BuildFinishStagesExecutor.runFinishStage(BuildFinishStagesExecutor.java:28)
        at jetbrains.buildServer.agent.impl.buildStages.BuildFinishStagesExecutor.doBuildFinishStages(BuildFinishStagesExecutor.java:20)
        at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:58)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:284)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:52)
        at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:248)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by msabramo** [comment]
so it looks like maybe `newTask` is `null` in this line (https://github.com/andreizhuk/tc-ansible-runner/blob/master/ansible-log-processor/src/main/java/ee/elinyo/teamcity/plugins/ansible/logparser/AnsibleOutputProcessor.java#L72):

``` java
70     private void nextTask(String line, long date) {
71         Task newTask = Task.fromOutputLine(line, date);
72         newTask.setOrder(taskCounter++);
73         if (currentTask != null) {
74             currentTask.setFinishedAt(date);
75         }
76         currentTask = newTask;
77     }
```

**Comment by msabramo** [comment]
Looking at https://github.com/andreizhuk/tc-ansible-runner/blob/master/ansible-log-processor/src/main/java/ee/elinyo/teamcity/plugins/ansible/logparser/domain/Task.java#L10, it looks like that could maybe happen if it's not finding a line in the output that matches the regular expression:

``` java
    private static final Pattern TASK_FIRST_LINE_PATTERN = Pattern
            .compile("^(TASK|NOTIFIED):\\s+\\Q[\\E(.+)\\Q]\\E");
```

**Comment by andreizhuk** [comment]
Thanks for trying the Ansible Runner and issue reporting!

The runner captures build output and publishes it as a hidden artifact, can be downloaded from build Artifacts tab. Can you see something like "ansible-run-raw-XXXX.log" in ".teamcity/ansible-runner" for the problematic build? If so, please attach it to the issue and I will take a look.

You can also try to debug it yourself. Just feed the raw output file to the [AnsibleOutputProcessor](https://github.com/andreizhuk/tc-ansible-runner/blob/master/ansible-log-processor/src/main/java/ee/elinyo/teamcity/plugins/ansible/logparser/AnsibleOutputProcessor.java). Check [SimpleTest](https://github.com/andreizhuk/tc-ansible-runner/blob/master/ansible-log-processor/src/test/java/ee/elinyo/teamcity/plugins/ansible/logparser/SimpleTest.java#L12) for inspiration.
